on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        exclude:
          - goarch: amd64
            goos: darwin
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.32
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: ./cmd/chimer/
        binary_name: chimer
        extra_files: chimes LICENSE README.md
        pre_command: apt update && apt install -y pkg-config clang libasound2-dev && export CGO_ENABLED=1 CC_FOR_darwin_amd64=clang CXX_FOR_darwin_amd64=clang++
        ldflags: -X main.build=${{ github.ref_name }}
        sha256sum: TRUE
        md5sum: FALSE
